#9 - implemented parent function with tests and docs
franciscop/react-test pull request #33
Opened 2020-05-04 15:04 UTC by vaske

Related Issue: #9 

- Implements .parent() Jest matcher method
- Adds tests to handle multiple cases
- Adds a README that includes the multiple cases
- Ran npm test to make sure nothing breaks
- Ran node docs/build to add to index.html

2020-05-04 15:33 UTC, franciscop commented on src/methods/parent/readme.md
> +## .parent()
Should be `###` [for the website](https://react-test.dev/).

2020-05-04 15:40 UTC, franciscop requested changes
Thanks for the PR! It looks good overall, but the selector logic should be changed to better follow jQuery's way of working.

2020-05-04 15:40 UTC, franciscop commented on src/methods/parent/index.js
> +  return this.find(selector).map((node) => node.parentNode);
If here is a selector, it should `filter` the parents it selects, not find children and then find their parents. e.g.:

```js
const base = $(
  <>
    <div><a>Hello</a></div>
    <span><a>World</a></span>
  </>
);
```

In here `$base.find('a').parent('div')` should select the first `<div>` and skip the `<span>`.

See [the jQuery documentation](https://api.jquery.com/parent/) for more info.

2020-05-04 20:16 UTC, vaske commented on src/methods/parent/index.js
> +  return this.find(selector).map((node) => node.parentNode);
Hey @franciscop sure thing will take a look, thanks for feedback ;)

2020-05-04 23:34 UTC, vaske commented on src/methods/parent/readme.md
> +## .parent()
fixed ;)

2020-05-04 23:36 UTC, vaske commented on src/methods/parent/index.js
> +  return this.find(selector).map((node) => node.parentNode);
@franciscop should we then implement `filter` function first and then use it or?

2020-05-05 00:47 UTC, franciscop commented on src/methods/parent/index.js
> +  return this.find(selector).map((node) => node.parentNode);
Internally it should probably be a `.map()` and then a `.filter()`, see [umbrella.js' `.parent()` implementation](https://github.com/franciscop/umbrella/blob/master/src/plugins/parent/parent.js).

2020-05-05 07:23 UTC, vaske commented on src/methods/parent/index.js
> +  return this.find(selector).map((node) => node.parentNode);
@franciscop yeah I checked umrella.js and tried that but something doesn't work will do some more debugging with it.

2020-05-20 12:43 UTC, vaske commented
@franciscop I added some changes please review :)

2020-05-26 22:03 UTC, franciscop commented on src/methods/parent/readme.md
> +  .first().nodeName;
This seems to be different from the tests where you do `.parent().nodeName`

2020-05-26 22:04 UTC, franciscop commented on src/methods/parent/index.js
> +  if (!selector) return this.first().parentNode;
We probably want to get the parent of each of the matched nodes, similar to jQuery and Umbrella JS, instead of the parent of the first child.

So we will need at least to `.map` all of the elements currently selected and move one up in the selector.

2020-05-26 22:13 UTC, vaske commented on src/methods/parent/index.js
> +  if (!selector) return this.first().parentNode;
should we traverse then bottom top? I tried to simulate/convert umbrella to our logic on exact same way but I got issues like can't do filter on map because map is not array in our case, not iterate error.

2023-12-02 00:03 UTC, franciscop commented
This was added here:
https://github.com/franciscop/react-test/pull/43

2023-12-02 00:03 UTC, closed without merging